language: python
python:
    - "2.7"

install: ./setup.sh
script: true
before_deploy: sed -i.bak 's/\[version\]/'"$TRAVIS_BRANCH-$TRAVIS_COMMIT"'/g' info.plist && zip -rv gitmoji.alfredworkflow *

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: gitmoji.alfredworkflow
  skip_cleanup: true
  on:
    tags: true